# **Week 4**


## A quiz

In [11]:
print("When did India gain its independence")
year= int(input())
if year == 1947:
    print("Correct")
else:
    print("You fool !!")

When did India gain its independence
Correct


### While loop

In [12]:
print("When did India gain its independence ?")
year= int(input())
while year != 1947:
    print("Incorrect \U0001F615")
    print("When did India gain its independence ?")
    year= int(input())
print("Correct")

When did India gain its independence ?
Incorrect  	u😕
When did India gain its independence ?
Incorrect  	u😕
When did India gain its independence ?
Correct


#### Factorial

In [5]:
print("Enter a number")
number = int(input())
factorial = 1
print(f"Factorial of {number} is ",end = "")
if number <0:
        print("Not defined")
else :
    while number != 0:
        factorial = factorial * number
        number = number - 1
    print(factorial)

Enter a number
Factorial of -99 is Not defined


#### Number of digits

In [10]:
print("Enter a number")
number = str(int(input())) ## just in case if the user enters a floting point number
digit = 0
if number !=0:
    digit = len(number)
print(digit)

Enter a number
3


In [11]:
# Let's do it with a while loop
number = abs(int(input("Enter a number")))
digits = 1
while number > 9:
    number = number // 10
    digits = digits + 1
print(digits)


2


### List

In [4]:
import random
l=[]
for i in range(100): # 100 numbers will be selected
    l.append(random.randint(0,10000))  # from 0,100000 and will be appended to l 
print(l)
print(len(l))

[9323, 8597, 7799, 7558, 9780, 2655, 9099, 6575, 1507, 5458, 2087, 164, 1744, 8070, 4716, 9197, 3778, 6234, 7340, 5280, 2092, 259, 2464, 4388, 7762, 3100, 510, 6661, 9396, 9797, 6401, 6430, 1964, 2103, 4716, 5550, 5651, 4660, 3138, 2490, 618, 1476, 4004, 7095, 1308, 8614, 1717, 714, 4393, 2069, 8490, 2701, 8022, 3552, 5690, 9901, 4407, 7438, 8848, 5079, 7062, 9692, 2079, 1355, 1511, 9254, 2790, 3396, 2807, 5212, 8971, 8072, 1521, 7856, 4936, 6282, 7752, 3257, 8118, 8132, 7412, 3273, 153, 3157, 8783, 5220, 7844, 9964, 5287, 8832, 458, 3019, 3408, 9795, 5230, 9116, 4253, 8863, 7789, 3941]
100


In [11]:
# Linear search in a list
l=[1,44,2,55,66,88,26,126,11,63,6161,11]
flag =0
number=int(input("Enter a number to be searched "))
for num in range(len(l)):
    if number == l[num]:
        print(f"{number} found at position {num}")
        flag =1
        break
if flag == 0:
    print("Number not found")

Number not found


In [96]:
# linear sorting
l=[1,16,11,61,61,61,611,4,44,0,416,46,0,325,654,46]
sorted_l=[]

while len(l)>0:
    minvalue = l[0]
    for i in range(len(l)):
        if l[i] < minvalue:
            minvalue = l[i]
    sorted_l.append(minvalue)
    l.remove(minvalue)
print(l)
print(sorted_l)



[]
[0, 0, 1, 4, 11, 16, 44, 46, 46, 61, 61, 61, 325, 416, 611, 654]


In [100]:
# bubble sort
import random
l=[]
for i in range(100):
    l.append(random.randint(0,200))
for i in range(len(l)):
    for j in range(len(l)-i-1):
        if l[j]>l[j+1]:
            l[j],l[j+1]=l[j+1],l[j]
        if l[j] == l[j+1]:
            l.remove(l[j]) # remove dublicate items, optional
print(l)


[1, 3, 19, 20, 22, 27, 28, 29, 33, 34, 35, 38, 39, 42, 45, 46, 48, 49, 50, 51, 53, 54, 59, 60, 62, 64, 69, 70, 72, 74, 77, 78, 79, 80, 82, 84, 85, 88, 89, 95, 97, 98, 101, 102, 103, 107, 110, 112, 115, 116, 117, 121, 123, 124, 125, 126, 127, 129, 131, 133, 134, 136, 138, 139, 140, 141, 146, 151, 154, 155, 156, 157, 159, 162, 163, 171, 177, 179, 183, 184, 185, 187, 188, 194, 198]


### Simple Dot product

In [106]:
l = [0,1,2,3,6,5,4,7,8,9]
m = [7,8,9,4,5,6,1,2,3,0]
result = 0
if len(l) == len(m):
    for i in range(len(l)):
       result += l[i]*m[i]
print(result)


140


### Matrix addition

In [110]:
l = [0,1,2,3,6,5,4,7,8,9]
m = [7,8,9,4,5,6,1,2,3,0]
result = []
if len(l) == len(m):
    for i in range(len(l)):
        result.append(l[i]+m[i])
print(result)

[7, 9, 11, 7, 11, 11, 5, 9, 11, 9]


In [131]:

r1 = [1,2,3,4,5,6,7,8,9]
r2 = [7,8,9,4,5,6,1,2,3]
r3 = [2,5,8,7,4,1,3,6,9]

m1 = [7,8,9,4,5,6,1,2,3]
m2 = [2,5,8,7,4,1,3,6,9]
m3 = [2,5,8,7,4,1,3,6,9]


A = []
B = []
C = [[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]
A = [r1,r2,r3]
B = [m1,m2,m3]



for i in range(3): # coulmn 
    for j in range(len(r1)): # row
        C[i][j] = (A[i][j]+B[i][j])
        
print(A)
print(B)

        
print(C) # list within a list




[[1, 2, 3, 4, 5, 6, 7, 8, 9], [7, 8, 9, 4, 5, 6, 1, 2, 3], [2, 5, 8, 7, 4, 1, 3, 6, 9]]
[[7, 8, 9, 4, 5, 6, 1, 2, 3], [2, 5, 8, 7, 4, 1, 3, 6, 9], [2, 5, 8, 7, 4, 1, 3, 6, 9]]
[[8, 10, 12, 8, 10, 12, 8, 10, 12], [9, 13, 17, 11, 9, 7, 4, 8, 12], [4, 10, 16, 14, 8, 2, 6, 12, 18]]


### Matrix Multiplication


In [137]:
import numpy as np
r1 = [1,2,3,4,5,6,7,8,9]
r2 = [7,8,9,4,5,6,1,2,3]
r3 = [2,5,8,7,4,1,3,6,9]
r4 = [1,2,3,4,5,6,7,8,9]
r5 = [7,8,9,4,5,6,1,2,3]
r6 = [2,5,8,7,4,1,3,6,9]
r7 = [1,2,3,4,5,6,7,8,9]
r8 = [7,8,9,4,5,6,1,2,3]
r9 = [2,5,8,7,4,1,3,6,9]

m1 = [7,8,9,4,5,6,1,2,3]
m2 = [2,5,8,7,4,1,3,6,9]
m3 = [2,5,8,7,4,1,3,6,9]
m4 = [7,8,9,4,5,6,1,2,3]
m5 = [2,5,8,7,4,1,3,6,9]
m6 = [2,5,8,7,4,1,3,6,9]
m7 = [7,8,9,4,5,6,1,2,3]
m8 = [2,5,8,7,4,1,3,6,9]
m9 = [2,5,8,7,4,1,3,6,9]

A = [r1,r2,r3,r4,r5,r6,r7,r8,r9]
B = [m1,m2,m3,m4,m5,m6,m7,m8,m9]

product = [[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]

for i in range(9):
    for j in range(len(r1)):
        for k in range(9):
            product[i][j] = product[i][j] + A[i][k]*B[k][j]
        
print(product)

print("\n\n")
A = np.mat(A)
B = np.mat(B)
print(A*B) # To verify

[[150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333], [150, 261, 372, 279, 192, 105, 111, 222, 333]]



[[150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]
 [150 261 372 279 192 105 111 222 333]]
